config/urls.py
from django.contrib import admin
from django.urls import path,include
from page.views import home_view
from user_profile.urls import login_view

urlpatterns = [
    
    path('admin/', admin.site.urls),
    
    path('', home_view,name="home_view"),
    
    #USER:
    path('user/',include('user_profile.urls',namespace="user") ),

]

user_profile/urls.py
from django.urls import path
from user_profile.views import login_view,logout_view,register_view


app_name = "user"
urlpatterns = [
    path('login/', login_view,name="login_view"),
    path('logout/', logout_view,name="logout_view"),
    #REGISTER:
    path('register/', register_view,name="register_view"),
]

blog/models.py
from django.db import models

# Create your models here.

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatar')
    twitter = models.CharField(max_length=200,null=True,blank=True)
    slug = models.SlugField(max_length=200)

blog/views.py
from django.shortcuts import render

# Create your views here.

page/views.py
from django.shortcuts import render

def home_view(request):
    context = dict()
    return render(request,"page/home_page.html",context )

user_profile/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from user_profile.models import Profile
from django.contrib import messages
from slugify import slugify

def login_view(request):
    # login olan user direkt olarak anasayfaya gidebilmeli
    context = dict(
    ) 
    if request.user.is_authenticated:
        messages.success(request,f" Heey! {request.user.username} daha önce giriş yapmıştınız")
        return redirect("home_view")
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        if len(username) < 6 or len(password) < 6:
            messages.warning(request,f"Kullanıcı adınız ya da parolanız geçersiz...")
        user = authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            messages.success(request,f" Heey! {request.user.username} Hoşgeldin!")
            return redirect("home_view")
        elif len(password) > 6 and user==None:
            messages.warning(request,f"Bir şeyler yanlış görünüyor!")

    return render(request,"user_profile/login.html",context)
      



def logout_view(request):
    messages.info(request,f" Heey! {request.user.username} Oturumun Sonlandı")
    logout(request)
    return redirect("/")

def register_view(request):
    context=dict()
    if request.method == "POST":
        post_info = request.POST
        email = post_info.get('email')
        email_confirm = post_info.get('email_confirm')
        password = post_info.get('password')
        password_confirm = post_info.get('password_confirm')
        first_name = post_info.get('first_name')
        last_name = post_info.get('last_name')
        twitter = post_info.get('twitter')
        if email != email_confirm:
            messages.warning(request,"Email adresleri Eşleşmedi...")
            return redirect ("user:register_view")
        if password != password_confirm:
            messages.warning(request,"Şifreler Eşleşmedi...")
            return redirect ("user:register_view")
        if len(email) < 3 or len(password) < 3 or len(first_name) < 3 or len(last_name) < 3:
            messages.warning(request,"Minimum karakter sayısını tamamlamalısınız...")
            return redirect ("user:register_view")

        user,created = User.objects.get_or_create(username=email)
        if not created:
            user_login = authenticate(request,username=email,password=password)
            if user is not None:
                messages.warning(request,"Daha önce kayıt olmuşsunuz... Ana Sayfaya Yönlendirildiniz...")
                login(request,user_login)
                return redirect("/")
            messages.warning(request,"Bu e-posta adresi zaten kayıtlı...")
            return redirect ("user:login_view")
        user.email= email
        user.first_name = first_name
        user.last_name =  last_name
        user.set_password(password)

        profile , profile_created = Profile.objects.get_or_create(user=user)
        profile.twitter = twitter
        profile.slug = slugify(f"{first_name}-{last_name}")
        user.save()
        profile.save()     
        messages.success(request,f"{user.first_name.title()} Kayıt Başarılı...")
        user_login = authenticate(request,username=email,password=password)
        login(request,user_login)
        return redirect('/')

    return render(request,"user_profile/register.html",context)
            

page/templates/page/home_page.html
{% extends 'core/base.html' %}



<h1>Home Page</h1>

templates/core/base_without_navbar.html
{% load static %}

<!doctype html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MD Clone</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
   
{% block content %}
{% endblock content %}
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/core/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} my-0 alert-dismissible fade show" role="alert">
    <strong  {% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }}
    {% endfor %}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

templates/core/navbar.html
 <!-- NAVBAR -->
 <nav class="navbar navbar-expand-lg bg border-bottom border-dark">
    <div class="container py-2">
        <a class="navbar-brand" href="#">MD Clone</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
                <a class="nav-link" aria-current="page" href="#">
                    Our story
                </a>
                <a class="nav-link" href="#">
                    Membership
                </a>
                <a class="nav-link" href="#">Write</a>
                {% if not request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'user:login_view' %}">Sign In</a>
                <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3" href="{% url 'user:register_view' %}">Get Started</a>
                {% else %}
                <a class="nav-link" href="#">{{ request.user.username }}</a>
                <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3" href="{% url 'user:logout_view' %}">Oturumu Kapat</a>

                {% endif %}

            </div>
        </div>
    </div>
</nav>
<!-- NAVBAR END -->

user_profile/templates/user_profile/login.html
{% extends 'core/base_without_navbar.html' %}
{% block content%}

{% include 'core/messages.html' %}
  <h2 class="text-center mt-5 "><strong>Giriş Yap </strong> </h2>

<div class="bg mt-4 py-5 border border-dark ">

  <div class="container px-5 ">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <form method="post">
          <!-- csrf_token,name ve method bilgisi olmalı(post methodu) -->
          {% csrf_token %}
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username">
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
          </div>
          <button type="submit" class="btn btn-dark">Login</button>
        </form>
      </div>
    </div>
  </div>
</div>
  {% endblock content%}

user_profile/templates/user_profile/register.html
{% extends 'core/base_without_navbar.html' %}
{% block content%}

{% include 'core/messages.html' %}
  <h2 class="text-center mt-5 "><strong>Kayıt Ol </strong> </h2>

<div class="bg mt-4 py-5 border border-dark ">

  <div class="container px-5 ">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <form method="post">
          <!-- csrf_token,name ve method bilgisi olmalı(post methodu) -->
          {% csrf_token %}
          <div class="mb-3">
            <label for="first_name" class="form-label">First Name</label>
            <input type="text" class="form-control" id="first_name"  name="first_name">
          </div>
          <div class="mb-3">
            <label for="last_name" class="form-label">Last Name</label>
            <input type="text" class="form-control" id="last_name"  name="last_name">
          </div>
          <div class="mb-3">
            <label for="email" class="form-label">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
          </div>
          <div class="mb-3">
            <label for="email_confirm" class="form-label">Email address-Confirm</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email_confirm">
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password-Confirm</label>
            <input type="password" name="password_confirm" class="form-control" id="exampleInputPassword1">
          </div>
          <div class="mb-3">
            <label for="twitter" class="form-label">Twitter Account</label>
            <input type="text" name="twitter" class="form-control" id="twitter">
          </div>
          <center>
              <a href="/" class="btn btn-secondary mx-5">Go Back</a>
              <button type="submit" class="btn btn-dark mx-5">Sign Up</button>
              <h5 class="mt-3">Already Have an Account ?</h5>
              <a type="submit" class="btn btn-dark  mx-5 mt-3" href="{% url 'user:login_view' %}">Login</a>
          </center>
        </form>
      </div>
    </div>
  </div>
</div>
  {% endblock content%}